### ISSUE TITLE
ESP with INMP441 freezes all the time

### ISSUE THREAD

**Issue by DivanX10** [Romkabouter/ESP32-Rhasspy-Satellite#125]
What could it be that the microphone freezes all the time? If you restart the ESP32, the microphone works, but not for long. In the topics, I see how the microphone reacts to sounds, and then it stops and nothing arrives in the topics
 
![image](https://user-images.githubusercontent.com/64090632/222161773-3e9dbfca-bb43-4ef1-ae79-fa7a8db24b0f.png)

I drew a diagram of how I connected INMP441 and MAX98357a to ESP 32 bathroom
-----
**Option 1. INMP441 microphone + ESP32 board**

![ESP32 Rhasspy Satellite - INMP441](https://user-images.githubusercontent.com/64090632/222166613-c1d69044-a7bc-451e-bbf9-87cbfaf6bf16.jpg)
-----
**Option 2. INMP441 microphone + MAX98357a sound amplifier + ESP 32 board.**

![ESP32 Rhasspy Satellite - INMP441 and MAX98357a](https://user-images.githubusercontent.com/64090632/222167241-2fc2e3ef-0317-40d6-9200-2dbaf239ded8.jpg)

-----
and also, how to connect the microphone correctly? I specified SiteID: esp-mic as in the screenshot and does not recognize my speech

![image](https://user-images.githubusercontent.com/64090632/222169193-67d7c1b3-3050-453f-9d77-5c2ab487eb38.png)
![image](https://user-images.githubusercontent.com/64090632/222169749-ec702201-293d-4eef-88b0-4e62634a86e1.png)

**Comment by mikey60** [comment]
I am having the same issue.  Did you find a solution?

**Comment by DivanX10** [comment]
> I am having the same issue. Did you find a solution?

I bought a ReSpeaker Core V2 that has 6 microphones, output to speakers and I forgot about this horror esp + microphone + speakers

**Comment by mikey60** [comment]
Thanks for the reply.

**Comment by ProrokWielki** [comment]
How long are you wires between ESP and mic (If they are too long, or run close to some high frequency source, it might mess up the mic communication)?
Could you also show logs from the esp? (data on the COM port)

**Comment by DivanX10** [comment]
> How long are your wires between ESP and mic (If they are too long, or run close to some high frequency source, it might mess up the mic communication)? Could you also show logs from the esp? (data on the COM port)

I used dupont wires 20 cm long. I am currently using ReSpeaker Core V2 with Rhasspy and unfortunately I will not be able to show you the logs, only if someone interested in this project provides it to you

**Comment by mikey60** [comment]
@ProrokWielki 
> How long are your wires between ESP and mic (If they are too long, or run close to some high frequency source, it might mess up the mic communication)? Could you also show logs from the esp? (data on the COM port)

I am using 100 mm wires for my breadboard.  At first the project was connected thorough a longer USB cable to a passive USB hub connected through  another USB cable to my desktop computer. With that configuration the microphone worked once and then I would have to restart the ESP32 to work again for one time.  I now have the project connected with a short USB cable to a 2.4 amp USB wall charger and the breadboard has been working reliably for several hours with out re-booting the ESP32.  Some of the wires of the bread board possibly moved some when connecting to the wall power source and eliminated an interference, but I am thinking the issue was due to a 5 volt voltage drop (I*R)  or noise at the ESP32 board when the speaker and LED were energized.  Thanks to Romkabouter and you for a great project!

**Comment by Romkabouter** [comment]
Ok great find. So this issue can be closed?

**Comment by mikey60** [comment]
I am okay with closing the issue, but I am not the original author.
